version = 3.11.1
maxColumn = 120
project.git = true
runner.dialect = scala212source3

# http://docs.scala-lang.org/style/scaladoc.html recommends the JavaDoc style.
# scala/scala is written that way too https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Predef.scala
docstrings.style = Asterisk
docstrings.blankFirstLine = fold
docstrings.wrap = false

# This also seems more idiomatic to include whitespace in import x.{ yyy }
spaces.inImportCurlyBraces = true
